//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeIPTVar
{
    using System;
    using System.Collections.Generic;
    
    public partial class Server
    {
        public int ServerID { get; set; }
        public string ServerLink { get; set; }
        public string ServerImage { get; set; }
        public string ServerDescription { get; set; }
        public int CategoryID { get; set; }
        public string ServerTitle { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
